ENDERECO_PARA_CEO = {
    "Al. Sd. Francisco Hierro, 100": "Santana",
    "Alameda Jequitibás, 100 (EEE Portal das Alamedas)": "Extremo Norte",
    "Alamedas das Oliveiras, 20 (EEE Portal das Oliveiras)": "Extremo Norte",
    "Alfredo Pujol, 930": "Santana",
    "Av. Ataliba Leonel x R. Ariosto César": "Santana",
    "Av. Ataliba Leonel, 2878": "Santana",
    "Av. Bandeirantes do Sul x R. das Gueixas": "Santana",
    "Av. Braz Leme, 2051": "Santana",
    "Av. Braz Leme, 2237": "Santana",
    "Av. Braz Leme, 2500": "Santana",
    "Av. Braz Leme, 3265": "Santana",
    "Av. Castelo Branco": "ITI7",
    "Av. Celestino (Travessa)": "Freguesia",
    "Av. Dr. Benedito Estevam dos Santos, 1274": "Santana",
    "Av. Dr. Benedito Estevam dos Santos, 295": "Santana",
    "Av. Dr. Benedito Estevam dos Santos, 965": "Santana",
    "Av. Eng. Caetano Álvares, 16": "Freguesia",
    "Av. Gen. Ataliba Leonel X Av. Santos Dumont": "Santana",
    "Av. Gen. Ataliba Leonel, 1440": "Santana",
    "Av. Gen. Ataliba Leonel, 2526": "Santana",
    "Av. Gen. Ataliba Leonel, 3267": "Santana",
    "Av. Gen. Ataliba Leonel, 3372": "Santana",
    "Av. Gen. Ataliba Leonel, 3598": "Santana",
    "Av. Gen. Ataliba Leonel, 3601": "Santana",
    "Av. João Paulo l, 221": "Freguesia",
    "Av. Lauzane Paulista, 119": "Freguesia",
    "Av. Leôncio de Magalhães x R. Amoroso Costa": "Santana",
    "Av. Leôncio de Magalhães x R. Pedro Madureira": "Santana",
    "Av. Leôncio de Magalhães x R. Prof. Fábio Fanucchi": "Santana",
    "Av. Leôncio de Magalhães, 1063": "Santana",
    "Av. Leôncio de Magalhães, 75": "Santana",
    "Av. Luiz Dumont Villares, 560": "Santana",
    "Av. Maestro Gabriel Migliori, 124": "Freguesia",
    "Av. Mal. Eurico Gaspar Dutra, 1623": "Santana",
    "Av. Min. Evandro Lins e Silva - Parque Cecap": "Guarulhos",
    "Av. Natalia Zarif, 121": "Guarulhos",
    "Av. Otaviano Alves de Lima, 109": "Freguesia",
    "Av. Tonico Lenci, 2476 (EEE - Vila Santa Rosa)": "Extremo Norte",
    "Av. Zaki Narchi, 52": "Santana",
    "Av. Zaki Narchi, 99": "Santana",
    "Av. das Bandeiras x R. Argentina (EEE Bandeiras)": "Extremo Norte",
    "Av. das Cerejeiras, 41": "Santana",
    "Av. das Cerejeiras, 509": "Santana",
    "Av. das Cerejeiras, 790": "Santana",
    "Av. Águas de São Pedro, 298": "Santana",
    "CT Pirituba": "Pirituba",
    "Corredor Norte-Sul, 153": "Santana",
    "EEE Alonso Sanches": "Guarulhos",
    "EEE Clube dos Metalúrgicos": "Guarulhos",
    "EEE Jardim Munira - R. Clarice Lispector, 374": "Guarulhos",
    "EEE Joana d'Arc - R. Ana do Sacramento Andrade, 15": "Santana",
    "EEE Morada do Sol": "Pirituba",
    "EEE Nova Caieiras II": "Extremo Norte",
    "EEE Nova Caieiras V": "Extremo Norte",
    "EEE Tenente Rocha - R. Tenente Rocha x Rua Heliodora": "Santana",
    "Estação Elevatória JU-13.11": "Extremo Norte",
    "Marginal Tietê, 77 (Casa Verde)": "Freguesia",
    "P013 - R. Prof. Suraia Aidar Menon, 1495": "ITI7",
    "Parque Domingos Luís, 100": "Santana",
    "Ponte Casa Verde (Sabesp Alça Casa Verde)": "Freguesia",
    "Ponte Piqueri": "Pirituba",
    "Ponto IT 3  PV 14": "Pirituba",
    "Ponto IT 3 - PV 01": "Pirituba",
    "Ponto IT 3 - PV 07": "Pirituba",
    "Ponto IT 3 - PV 08": "Pirituba",
    "Pr. Pres. Jânio da Silva Quadros, 155": "Santana",
    "Pr. Pres. Jânio da Silva Quadros, 465": "Santana",
    "Pr. Pres. Jânio da Silva Quadros, 871": "Santana",
    "Praça da Emancipação Prefeito Gino Dartora, 5 (EEE Nova Caieiras III)": "Extremo Norte",
    "R. Afonso Cunha, 807": "Guarulhos",
    "R. Alferes Magalhães x Av. Cruzeiro do Sul": "Santana",
    "R. Alferes Magalhães, 377": "Santana",
    "R. Alfredo Pujol, 1230": "Santana",
    "R. Alfredo Pujol, 55": "Santana",
    "R. Alm. Noronha, 748 (Proximo à Viela)": "Santana",
    "R. Arari Leite, 629": "Santana",
    "R. Azir Antônio Salton, 247": "Santana",
    "R. Balsa x R. Eng. Edgard Ferreira de Barros Júnior": "Freguesia",
    "R. Barra da Jangada, 285": "Santana",
    "R. Barra da Jangada, 71": "Santana",
    "R. Borges Ladário, 209": "Santana",
    "R. Capitão Rabelo, 305": "Santana",
    "R. Cardeal, 653A (EEE Laranjeiras)": "Extremo Norte",
    "R. Carlos Camargo Aranha, 164": "Santana",
    "R. Cel. Marcílio Franco, 1195": "Santana",
    "R. Conceição da Barra, 370": "Santana",
    "R. Conselheiro Moreira de Barros, 901": "Santana",
    "R. Cônego Manuel Vaz x R. Daniel Rossi": "Santana",
    "R. Dona Albertina Domingos, 49": "Santana",
    "R. Dona Luísa Scarpini, 528": "Santana",
    "R. Donata, 2": "Santana",
    "R. Dr. Cesar, 107": "Santana",
    "R. Dr. Cesár, 1277": "Santana",
    "R. Dr. Cesár, 994": "Santana",
    "R. Dr. César, 370": "Santana",
    "R. Dr. César, 818": "Santana",
    "R. Dr. Olavo Egídio, 1008": "Santana",
    "R. Dr. Vidal Reis, 294": "Santana",
    "R. Duarte de Azevedo, 489": "Santana",
    "R. Durval Clemente, 329": "Santana",
    "R. Emanuele Saporiti x R. Porangatu": "Santana",
    "R. Eulália Bastos, 157": "Santana",
    "R. Evaristo Roque, 18": "Freguesia",
    "R. Ezequiel Freire, 17": "Santana",
    "R. Ezequiel Freire, 483": "Santana",
    "R. Força Pública, 355": "Santana",
    "R. Francisco Fanganielo, 300": "Santana",
    "R. Gaspar Soares, 314": "Santana",
    "R. Gaspar Soares, 415": "Santana",
    "R. Gen. Bagueira, 115": "Santana",
    "R. Gen. Bagueira, 250": "Santana",
    "R. Gen. João Carlos Lobo Botelho x R. Benedita Dornelas": "Santana",
    "R. Gilberto Sampaio x R. Pedro Cacunda": "Santana",
    "R. Iapucanin, 10": "Santana",
    "R. Inglesa, 303": "Santana",
    "R. Joaquim Norberto x R. Horácio Scrosoppi": "Santana",
    "R. Joaquim Norberto, 201": "Santana",
    "R. Joaquim Norberto, 262": "Santana",
    "R. Joaquim Rodrigues Costa, 171": "Santana",
    "R. José Debieux, 50": "Santana",
    "R. José Peres Campelo, 120": "Pirituba",
    "R. José da Silva, 309 (EEE P3)": "Extremo Norte",
    "R. José de Albuquerque, 2": "Santana",
    "R. Jovita, 60": "Santana",
    "R. João Antônio da Silva, 70 (EEE Final Lavapés)": "Extremo Norte",
    "R. Julia Lopes de Almeida x Av. Mal. Eurico Gaspar Dutra": "Santana",
    "R. Juncal, 255": "Santana",
    "R. Kaneda, 621": "Santana",
    "R. Luís Pedroso, 1": "Santana",
    "R. Léo Ribeiro de Moraes, 15": "Freguesia",
    "R. Maestro Otto Way, 111 (EEE Itatinga II)": "Freguesia",
    "R. Maestro Otto Wey, 33": "Freguesia",
    "R. Magalhães Lemos, 220 (EEE Caiuba)": "Pirituba",
    "R. Mal. Hermes da Fonseca, 345": "Santana",
    "R. Mal. Hermes da Fonseca, 486": "Santana",
    "R. Manajeru, 39": "Santana",
    "R. Manoel Reis da Silva, 93": "Guarulhos",
    "R. Manoel de Carvalho, 366": "Freguesia",
    "R. Marechal Gaspar Dutra (EEE Eusébio Av. dos Coqueiros)": "Extremo Norte",
    "R. Maria Curupaiti, 280": "Santana",
    "R. Maria Curupaiti, 706": "Santana",
    "R. Maria Cândida, 25": "Santana",
    "R. Maria Cândida, 428": "Santana",
    "R. Maria Quedas, 366": "Santana",
    "R. Maria, 28": "Santana",
    "R. Meira, 580": "Guarulhos",
    "R. Miguel Casagrande, 107": "Freguesia",
    "R. Miguel Fernandes Maldonado, 160": "Guarulhos",
    "R. Mira Estrela, 311": "Santana",
    "R. Moreno, 328": "Guarulhos",
    "R. Narciso Degrandi, 277 (EEE Vila Rosina)": "Extremo Norte",
    "R. Narita, 13": "Santana",
    "R. Narita, 195": "Santana",
    "R. Neves Paulista, 125": "Santana",
    "R. Neves Paulista, 45": "Santana",
    "R. Osaka, 1000": "Santana",
    "R. Osaka, 1350": "Santana",
    "R. Osaka, 753": "Santana",
    "R. Otto Labastille (Praça Dona Amália Guilhermina Solitari)": "Freguesia",
    "R. Outeiro da Cruz, 246": "Santana",
    "R. Outeiro da Cruz, 315": "Santana",
    "R. Outeiro da Cruz, 415": "Santana",
    "R. Padre Celestino André Trevisan, 239 (EEE Suisso)": "Extremo Norte",
    "R. Padre Ildefonso": "Santana",
    "R. Paulo Avelar, 5": "Santana",
    "R. Paulo Maldi, 392": "Santana",
    "R. Pedro Cacunda, 547": "Santana",
    "R. Pedro Taques Píres, 38": "Santana",
    "R. Piatá, 1": "Santana",
    "R. Piatá, 1500": "Santana",
    "R. Piatá, 910": "Santana",
    "R. Prof. Antônio Pena, 54": "Santana",
    "R. Professor Fábio Fanucchi x Pq. São Domingos": "Santana",
    "R. Professor Fábio Fanucchi, 425": "Santana",
    "R. Professor Joaquim Osório de Azevedo, 118": "Santana",
    "R. Quedas, 288": "Santana",
    "R. Roque Soares Medella, 64": "Santana",
    "R. Samurais x R. Mussumés": "Santana",
    "R. Samurais, 485": "Santana",
    "R. Santo Antônio do Aventureiro, 280": "Guarulhos",
    "R. Sapienza, 115": "Santana",
    "R. Sd. Abel Antônio Medanha, 10": "Santana",
    "R. Sd. Anésio Antão Ferreira x R. Cabo João Monteiro da Rocha": "Santana",
    "R. Sd. José Antônio Moreira, 26": "Santana",
    "R. Sd. José Antônio Moreira, 281": "Santana",
    "R. Sd. José Higaskino x Av. Bandeirantes do Sul": "Santana",
    "R. Serafim Poli, 286": "Santana",
    "R. Sevilha, 45": "Santana",
    "R. Sobral Júnior, 371": "Santana",
    "R. Ten. Rocha, 146": "Santana",
    "R. Ten. Rocha, 392": "Santana",
    "R. Tenente Blum, 71": "Santana",
    "R. Tibiri x R. Gaspar Soares": "Santana",
    "R. Tibério 171 (EEE Alexandre Magno)": "Extremo Norte",
    "R. Togo, 171": "Santana",
    "R. Urupiara x R. Antônio dos Santos Neto": "Santana",
    "R. Voluntários da Pátria x R. Alfredo Pujol": "Santana",
    "R. Voluntários da Pátria x R. Mal. Odylio Denys": "Santana",
    "R. das Flores de Maio, 787 (EEE P4)": "Extremo Norte",
    "R. das Gueixas, 110": "Santana",
    "R. do Tramway, 1000": "Santana",
    "R. do Tramway, 114": "Santana",
    "R. p/ de Minas, 208": "Freguesia",
    "Sargento-Mor Ramalho, 34": "Santana",
    "Sd. R. Francisco Tamborim, 213": "Santana",
    "Tv. Carnaval de Veneza, 1": "Santana",
    "Tv. Casalbuono x Marginal Tietê": "Santana",
    "Tv. Oswaldo Nazareno Lupattelli, 100": "Santana",
    "Tv. Pietro Pandolfo x Av. Gen. Edgar Facó": "Freguesia",
    "Tv. Três Idades, 10": "Santana",
    "R. Prof. Suraia Aidar Menon, 1495": "ITI7",
    "R. dos Cravos, 136": "Extremo Norte"
}